### ISSUE TITLE
Error in conversion

### ISSUE THREAD

**Issue by Jamalhazem98** [rokubun/android_rinex#6] opened 2019-09-18 12:34 UTC
Hi
i'm trying to convert the input log from data folder but I keep on getting this message
what's wrong?
Thanks a lot
![k](https://user-images.githubusercontent.com/45419447/65148835-3a653d00-da21-11e9-9b03-d32c7514744d.PNG)

**Comment by anumerico** [comment] 2020-05-05 15:39
@Jamalhazem98 I'm getting a similar error, what's funny is it works with log files I've got from February but doesn't with the ones i'm getting today. Any clue?

**Comment by anumerico** [comment] 2020-05-07 08:52
@Jamalhazem98 . That's due to Glonass svid defaulting to FCN instead of OSN, the program does the right thing which is skipping that satellite, the problem is that then it doesn't resume to its normal functioning and it halts. Any help? Did you manage to sort it out?

**Comment by alexlopezc** [comment] 2020-06-24 13:22
Hi,

This issue has been fixed in commit [e3051892a3902ad9e7753cd679dad986ce1e081f](https://github.com/rokubun/android_rinex/commit/e3051892a3902ad9e7753cd679dad986ce1e081f)

Thank for using the tool

**Closed as completed by alexlopezc** 2020-06-24 13:22 UTC
